20210908 bl project init
LinkerApplication/cv-generator pull request #18
Opened 2021-09-08 19:21 UTC by ssyucfa

2021-09-08 19:22 UTC, artemjasan commented
Тебе надо ещё в .gitignore добавить .index/

2021-09-08 19:24 UTC, ssyucfa commented
> Тебе надо ещё в .gitignore добавить .index/

добавил

2021-09-08 20:20 UTC, aidynsemey7sk commented on backend/config/auto_docs_urls.py
> +schema_view = get_schema_view(
Первый раз вижу такое, я так понял это DRF?

2021-09-08 20:45 UTC, artemjasan requested changes

2021-09-08 20:45 UTC, artemjasan commented on .gitignore
> +.idea/
несмотря на то что ты добавил это в гитигноре, файлы были уже затреканы и закосичены
решение проблемы:
https://stackoverflow.com/questions/1139762/ignore-files-that-have-already-been-committed-to-a-git-repository

2021-09-08 20:45 UTC, artemjasan commented on backend/config/asgi.py
> +https://docs.djangoproject.com/en/3.2/howto/deployment/asgi/
все ненудные коммпентарии удаляются

2021-09-08 20:45 UTC, artemjasan commented on .gitignore
> +.index/
не хватает пустой строки в конце файла

2021-09-08 20:45 UTC, artemjasan commented on backend/config/settings.py
> +
общие комментарии-шапки удалить

2021-09-08 20:45 UTC, artemjasan commented on backend/config/auto_docs_urls.py
> +from django.urls import path
У нас еще нет описания ендпоитов и на данном этапе это лишнее, я бы пока удалил эту библиоку. Файл тоже

2021-09-08 20:45 UTC, artemjasan commented on backend/config/settings.py
> +# Quick-start development settings - unsuitable for production
удалить

2021-09-08 20:45 UTC, artemjasan commented on backend/config/settings.py
> +INSTALLED_APPS = [
правильно будет вот так их обозначить Django internal applications

2021-09-08 20:45 UTC, artemjasan commented on backend/config/settings.py
> +    # other apps
3rd party applications

2021-09-08 20:45 UTC, artemjasan commented on backend/config/settings.py
> +    # our apps
Internal applications

2021-09-08 20:45 UTC, artemjasan commented on backend/config/settings.py
> +
internal идут первее 3rd party

2021-09-08 20:45 UTC, artemjasan commented on backend/config/settings.py
> +# DATABASES = {
я бы пока оставил стандарт с скулайт3 пока еще ничего нету

2021-09-08 20:45 UTC, artemjasan commented on backend/config/settings.py
> +# Static files (CSS, JavaScript, Images)
удалить

2021-09-08 20:45 UTC, artemjasan commented on backend/config/settings.py
> +# Default primary key field type
удалить

2021-09-08 20:45 UTC, artemjasan commented on backend/config/settings.py
> +# Internationalization
удалить

2021-09-08 20:45 UTC, artemjasan commented on backend/config/urls.py
> +from .auto_docs_urls import urlpatterns as swagger
пока не нужен

2021-09-08 20:45 UTC, artemjasan commented on backend/config/urls.py
> +urlpatterns += [
это не нужно, так как у нас будет тут только урл проекта и приложений

2021-09-08 20:45 UTC, artemjasan commented on backend/config/urls.py
> +# swagger urls
свагер тоже ока лишний

2021-09-08 20:45 UTC, artemjasan commented on backend/config/urls.py
> +
оставляем по павилам только 1 пустую строчку в конце, пайчарм обычно подсказывает

2021-09-08 20:45 UTC, artemjasan commented on backend/config/wsgi.py
> +It exposes the WSGI callable as a module-level variable named ``application``.
удалить

2021-09-08 20:45 UTC, artemjasan commented on backend/pyproject.toml
> +drf-yasg = "^1.20.0"
пока в нем нет необходмости

2021-09-08 20:45 UTC, artemjasan commented on backend/pyproject.toml
> +[tool.poetry.dev-dependencies]
так как сейчас идет период разработки то необходимо все перенести в дев зависимости

2021-09-08 20:45 UTC, artemjasan commented on backend/config/settings.py
> +SECRET_KEY = 'django-insecure-na!-$y#1zbs%0*f(1e=3rxl(%(kme2v=1ohh74c77wf#-cfxhp'
такие вещи нельзя хранить в открытом доступе. Можно использовать библиотеку dotenvд или os.getenv.

Я люблю первый вариант, Павел - второй. Но тут @vrppaul реши ты)

2021-09-08 20:52 UTC, artemjasan commented
> > Тебе надо ещё в .gitignore добавить .index/
> 
> добавил

посмотри в комментариях,  я скинул решение проблемы

2021-09-08 20:53 UTC, vrppaul commented on backend/config/settings.py
> +SECRET_KEY = 'django-insecure-na!-$y#1zbs%0*f(1e=3rxl(%(kme2v=1ohh74c77wf#-cfxhp'
да пока можно так оставить, потом переделаем, у нас все равно прода нет

2021-09-08 21:14 UTC, vrppaul requested changes
у меня лишь пара комментариев сверху к комментам Артема

основная претензия: у нас в корне папки backend будут находится лишь файлы настроек, все питон файлы у нас должны находиться в папке проекта. то есть переместить все, что касается самого джанго в папку, которую можно назвать `generator`, например
в корне оставить игнор и поетри файлы

также я бы переименовал config на core, потому что в config я бы ожидал увидеть конфигурационные файлы, а не основу проекта

2021-09-08 21:14 UTC, vrppaul commented on backend/config/asgi.py
> +application = get_asgi_application()
я не уверен, что нам вообще ASGI файл понадобится, у нас будет синхронное приложение

2021-09-08 21:14 UTC, vrppaul commented on backend/config/auto_docs_urls.py
> +from django.urls import path
поддерживаю

2021-09-08 21:14 UTC, vrppaul commented on backend/config/settings.py
> +# DATABASES = {
пока дб нет, можно все так закоментированно оставить

2021-09-09 12:50 UTC, ssyucfa commented on backend/pyproject.toml
> +drf-yasg = "^1.20.0"
в чем?

2021-09-09 15:14 UTC, vrppaul requested changes

2021-09-09 15:14 UTC, vrppaul commented on backend/pyproject.toml
> +drf-yasg = "^1.20.0"
в ясге. пока рано это решать

2021-09-09 15:14 UTC, vrppaul commented on backend/pyproject.toml
> +python = "^3.9"
мы точно хотим локать для всех версию питона на 3.9?

2021-09-09 15:14 UTC, vrppaul commented on backend/project/core/urls.py
> +urlpatterns += swagger
все это можно смело убрать

2021-09-09 15:14 UTC, vrppaul commented on backend/project/core/urls.py
> +from .auto_docs_urls import urlpatterns as swagger
пока не нужно

2021-09-09 15:14 UTC, vrppaul commented on backend/project/core/auto_docs_urls.py
> +]
лишний файл

2021-09-09 15:14 UTC, vrppaul commented on backend/project/core/asgi.py
> +application = get_asgi_application()
у нас будет что-то асинхронное?

2021-09-09 15:19 UTC, ssyucfa commented
У меня никак не получается убрать idea, при этом пустая папка frontend не убирается, кто то может склонировать, и исправить эти проблемы?

2021-09-09 16:14 UTC, vrppaul requested changes

2021-09-09 16:14 UTC, vrppaul commented on backend/generator/core/urls.py
> +from .auto_docs_urls import urlpatterns as swagger
этого больше нет - удалить

2021-09-09 16:14 UTC, vrppaul commented on backend/generator/core/urls.py
> +]
пока можно удалить

2021-09-09 16:14 UTC, vrppaul commented on backend/pyproject.toml
> +drf-yasg = "^1.20.0"
удалить эту зависимость

2021-09-11 10:03 UTC, vrppaul approved these changes

2021-09-11 10:09 UTC, artemjasan requested changes

2021-09-11 10:09 UTC, artemjasan commented on backend/generator/core/settings.py
> +    'drf_yasg',
Я дум это точно можно удалить, если нет зависимости

2021-09-11 10:10 UTC, vrppaul commented on backend/generator/core/settings.py
> +    'drf_yasg',
точно, хорошо заметил

2021-09-11 10:35 UTC, artemjasan approved these changes

2021-09-11 14:20 UTC, merged