created app and model
LinkerApplication/cv-generator pull request #21
Opened 2021-09-12 15:49 UTC by ssyucfa

Создал приложение и модель профиль

2021-09-12 19:38 UTC, artemjasan requested changes

2021-09-12 19:38 UTC, artemjasan commented on .idea/cv-generator.iml
> +<?xml version="1.0" encoding="UTF-8"?>
снова лишнее

2021-09-12 19:38 UTC, artemjasan commented on .idea/inspectionProfiles/profiles_settings.xml
> +<component name="InspectionProjectProfileManager">
туда же

2021-09-12 19:38 UTC, artemjasan commented on .idea/modules.xml
> +<?xml version="1.0" encoding="UTF-8"?>
всю папку надо в гитигноре

2021-09-12 19:38 UTC, artemjasan commented on backend/generator/account/models.py
> +    about_me = models.TextField()
я бы дал ограничение 255, как по старинке)

2021-09-13 20:02 UTC, artemjasan commented on backend/generator/account/models.py
> +    email = models.EmailField(max_length=150)
Мне кажется в имейле можно смело и 50 дать, я что-то не припомню больше 35-40 знаков даже

2021-09-13 20:04 UTC, artemjasan commented on backend/generator/account/models.py
> +    experience = models.PositiveSmallIntegerField(default=0)
Я немного не понял что тут должно быть? Просто года опыта?

2021-09-13 20:05 UTC, artemjasan commented
Я написал ещё пару комментариев и на этом у меня нету больше вопросы.
@vrppaul  у тебя есть?

2021-09-13 20:23 UTC, vrppaul requested changes
основная претензия еще в том, что у тебя модель называется `Profile`, а приложение `account`. я бы оставил `profile` оба, чтобы все было одинаково

2021-09-13 20:23 UTC, vrppaul commented on .gitignore
> +
вот тут у тебя возникнет мердж конфликт, так как я изменил мастера сегодня, чтобы там было это. примерджни себе нового мастера и потом замерджи в свою ветку. придется решить мердж конфликт, правда

2021-09-13 20:23 UTC, vrppaul commented on backend/generator/account/models.py
> +    experience = models.PositiveSmallIntegerField(default=0)
да, я тоже не понял, что здесь должно быть

2021-09-13 20:23 UTC, vrppaul commented on backend/generator/account/models.py
> +    full_name = models.CharField(max_length=255)
я еще подумал. не будет ли лучше разделить на name и surname? потому что в таком случае мы сможем сделать, чтобы у всех отображалось в порядке name surname
если пользователь будет писать в любовольном порядке, то у всех может быть по разному

2021-09-13 20:23 UTC, vrppaul commented on backend/generator/account/models.py
> +    number = models.CharField(15)
15 точно хватит?

2021-09-13 20:23 UTC, vrppaul commented on backend/generator/account/models.py
> +    website = models.URLField()
вот эти три филда я бы оставил возможность не указывать, потому что не все хотят делиться телефоном, не  у всех есть вебсайт, и не всем есть, что написать о себе

2021-09-13 20:23 UTC, vrppaul commented on backend/generator/account/models.py
> +
здесь отсутствует связь 1к1 с юзером

2021-09-13 20:23 UTC, vrppaul commented on backend/generator/account/admin.py
> +# Register your models here.
можно сразу зарегистрировать профиль, я думаю

2021-09-13 20:36 UTC, ssyucfa commented on backend/generator/account/models.py
> +    number = models.CharField(15)
да

2021-09-13 20:36 UTC, ssyucfa commented on backend/generator/account/models.py
> +    website = models.URLField()
окей\

2021-09-13 20:36 UTC, ssyucfa commented on backend/generator/account/models.py
> +
еще юзера же нету

2021-09-13 20:37 UTC, ssyucfa commented on backend/generator/account/admin.py
> +# Register your models here.
окей

2021-09-13 20:37 UTC, ssyucfa commented on backend/generator/account/models.py
> +    experience = models.PositiveSmallIntegerField(default=0)
ну да, просто опыт в годах, а что еще?

2021-09-13 20:37 UTC, ssyucfa commented on backend/generator/account/models.py
> +    email = models.EmailField(max_length=150)
на всяк случай можно оставить

2021-09-13 20:39 UTC, ssyucfa commented on backend/generator/account/models.py
> +    full_name = models.CharField(max_length=255)
text hide просто оставить можно, а то и так и так могут ошибитьтся, здесь разницы не будет как по мне

2021-09-13 20:40 UTC, ssyucfa commented on .gitignore
> +
profile приложение назвать? ну да, в принципе логично

2021-09-13 20:40 UTC, vrppaul commented on backend/generator/account/models.py
> +
зато есть лучше, есть `settings.AUTH_USER_MODEL` ;)

2021-09-13 20:41 UTC, vrppaul commented on backend/generator/account/models.py
> +
почитай, как референцить кастомного юзера

2021-09-13 21:09 UTC, vrppaul commented on backend/generator/account/models.py
> +    experience = models.PositiveSmallIntegerField(default=0)
а опыт в чем? что если человек сначала был дизайнером, а потом программистом. как тогда опыт считать?

2021-09-13 21:10 UTC, vrppaul commented on backend/generator/account/models.py
> +    full_name = models.CharField(max_length=255)
да в принципе можно оставить и так. думаю, что пока что это не принципиально

2021-09-14 16:45 UTC, artemjasan commented on backend/generator/account/models.py
> +    experience = models.PositiveSmallIntegerField(default=0)
Я бы создал ещё одну модель, место работы и привязал бы ее сюда

2021-09-14 16:55 UTC, vrppaul commented on backend/generator/account/models.py
> +    experience = models.PositiveSmallIntegerField(default=0)
да, можно что-то типа такого сделать потом

2021-09-14 19:27 UTC, vrppaul requested changes

2021-09-14 19:27 UTC, vrppaul commented on backend/generator/profile/models.py
> +    website = models.URLField(blank=True)
Совсем незначительная вещь: поля тоже лучше делать в алфавитном порядке, так будет легче искать нужный

2021-09-14 19:35 UTC, ssyucfa commented on backend/generator/profile/models.py
> +    website = models.URLField(blank=True)
эх, вот бы узнать алфавит английского, а можно и русского))

2021-09-14 19:37 UTC, vrppaul approved these changes
Можешь мерджить squash and merge

2021-09-14 19:40 UTC, artemjasan approved these changes

2021-09-14 19:42 UTC, merged