Create app accaunts
LinkerApplication/cv-generator pull request #22
Opened 2021-09-13 15:01 UTC by aidynsemey7sk

Create an account app and create a custom model by subclassing AbstractUser

2021-09-13 18:10 UTC, ssyucfa commented
Назови приложение account

2021-09-13 20:11 UTC, artemjasan commented
> Назови приложение account

+1

2021-09-13 20:31 UTC, artemjasan commented
Я бы ещё добавил сериализатор (смотри drf) и указал какие поля необходимо сериализации подвергнуть.

2021-09-13 20:33 UTC, artemjasan commented
Пока много чего не хватает, постарайся найти инфы - я много нашел по запросам: 
Custom user drf email only - что-нибудь такое топорное, если что скину завтра если все глухо будет

2021-09-13 20:34 UTC, artemjasan requested changes

2021-09-13 20:34 UTC, artemjasan commented on backend/generator/accounts/admin.py
> +
Необходима регистрация модели. Посмотри в мануалах Джанго - все модели которые мы создаём для работы с бд должны быть зареганы

2021-09-13 20:34 UTC, artemjasan commented on backend/generator/accounts/admin.py
> +
Подумай над тем какая должна быть регистрация. Я нашел несколько примеров которые бы подошли прямо нам +-

2021-09-13 20:34 UTC, artemjasan commented on backend/generator/accounts/apps.py
> +
Изменить названия, как писал Ваня

2021-09-13 20:34 UTC, artemjasan commented on backend/generator/accounts/models.py
> +    username = None
Мне казалось у нас было обговорено больше информации = больше полей которые содержит модель юзера, ведь мы их потом будем использовать для автозаполнения формы

2021-09-13 20:34 UTC, artemjasan commented on backend/generator/accounts/models.py
> +    username = None
На вскидку там был телефон, веб-сайт (мне кажется должен быть, почему нет) итд

2021-09-13 20:34 UTC, artemjasan commented on backend/generator/core/settings.py
Мы договорились использовать JWT аутентификацию, но у тебя ничего об этом ничего нету.

2021-09-13 20:34 UTC, artemjasan commented on backend/generator/core/settings.py
Также необходимо указать кастом модель в сеттингах так как Джанго не знает какую конфигурацию кастом юзера мы используем + есть дополнительные настройки для полей (какие поля реквайр, какие нет)

2021-09-13 20:34 UTC, artemjasan commented on backend/generator/core/settings.py
При использовании библиотек Django-allauth и Django-rest-auth там необходимо указать ещё дополнительно настройки

2021-09-13 20:41 UTC, ssyucfa commented on backend/generator/accounts/models.py
> +    username = None
так это все в profile

2021-09-13 20:42 UTC, ssyucfa commented on backend/generator/core/settings.py
аутентификацию позже вроде бы решили сделать

2021-09-13 20:45 UTC, artemjasan commented on backend/generator/core/settings.py
Дада, я перестал малость, сейчас удалю лишнее

2021-09-13 20:48 UTC, vrppaul commented on backend/generator/accounts/models.py
> +    username = None
@ssyucfa прав

2021-09-13 20:52 UTC, vrppaul commented on backend/generator/accounts/apps.py
> +
я не особо согласен с названием аппки accounts. оно совершенно не отражает суть аппки, а аппка буквально заменяет юзера. так что я бы все-таки советовал назвать аппку `users`

2021-09-13 20:54 UTC, artemjasan commented on backend/generator/accounts/models.py
> +    username = None
Да, это точно, я перепутал.
Что бы я здесь добавил это только то что емайл должен быть уникальным, так как у не используется username, и соответственно уникальный теперь имейл

2021-09-13 21:01 UTC, vrppaul requested changes
проект лучше переименовать, как я указал в одном из комментов

2021-09-13 21:01 UTC, vrppaul commented on backend/generator/accounts/tests.py
> +# Create your tests here.
у нас будут тесты для юзера? если будут, то я бы их не клал в один файл, и имплементировал уже потом

2021-09-14 13:59 UTC, aidynsemey7sk commented on backend/generator/accounts/tests.py
> +# Create your tests here.
удалил файл test.py

2021-09-14 14:14 UTC, aidynsemey7sk commented on backend/generator/accounts/apps.py
> +
Изменил на users

2021-09-14 14:16 UTC, aidynsemey7sk commented on backend/generator/accounts/models.py
> +
Две пустые строки есть

2021-09-14 17:24 UTC, artemjasan requested changes

2021-09-14 17:24 UTC, artemjasan commented on backend/generator/accounts/models.py
> +
Я вижу одну

2021-09-15 06:58 UTC, artemjasan requested changes

2021-09-15 06:58 UTC, artemjasan commented on backend/generator/users/models.py
> +class User(AbstractUser):
@vrppaul поправь меня если что, но мне кажется лучше не называть кастомный класс юзера  User, лучше будет CustomUser

2021-09-15 09:54 UTC, vrppaul requested changes
нужно еще немного добавить в модель юзера

2021-09-15 09:54 UTC, vrppaul commented on backend/generator/users/models.py
> +class User(AbstractUser):
да пойдет и так. мы везде все равно будет из сеттингов брать эту модель

2021-09-15 09:54 UTC, vrppaul commented on backend/generator/users/models.py
> +    email = models.EmailField(unique=True)
вот тут посмотри еще, как советуют делать: https://stackoverflow.com/a/43209322/14645104
потом протестируй, попробуй создать суперюзера, будет ли работать

2021-09-15 09:55 UTC, vrppaul commented
тебе придется еще примерджить себе актуального мастера и решить мердж конфликт

2021-09-15 15:27 UTC, closed without merging