Basic dockerezation of the backend
LinkerApplication/cv-generator pull request #25
Opened 2021-09-17 18:47 UTC by artemjasan

Добевлена базовая докеризация проектаю

- Билд пока только в одну стадию, так как в две нам не потребуется пока. Все же байсик вариантю.
- pg-admin не стал добавлять, но если будет нужно то могу добавить

2021-09-17 20:40 UTC, vrppaul requested changes
я бы переименовал еще `Dockerfile` -> `Dockerfile.dev`

2021-09-17 20:40 UTC, vrppaul commented on backend/Dockerfile
> +ENV POETRY_VERSION=1.1.8
а мы точно хотим залочить версию?

2021-09-17 20:40 UTC, vrppaul commented on backend/Dockerfile
> +ENV PIP_DISABLE_PIP_VERSION_CHECK=on
это разве не значит, что отключается оповещение, что пип надо обновить?
не лучше тогда будет или залочить версию пипа в зависимости от версии питона, или всегда его апдейтить?

2021-09-17 20:40 UTC, vrppaul commented on backend/Dockerfile
> +ENV PIP_DISABLE_PIP_VERSION_CHECK=on
ты просто ниже апгрейдишь пип уже

2021-09-17 20:40 UTC, vrppaul commented on backend/Dockerfile
> +RUN pip install --no-cache-dir "poetry==$POETRY_VERSION"
а что не в одной команде?

2021-09-17 20:40 UTC, vrppaul commented on backend/Dockerfile
> +COPY poetry.lock pyproject.toml /backend/
достаточно уже сделать `.` вместо `/backend`

2021-09-17 20:40 UTC, vrppaul commented on backend/Dockerfile
> +COPY . /backend/
опять же достаточно `COPY . .`, ты уже в бэкенде

2021-09-17 20:40 UTC, vrppaul commented on backend/Dockerfile
> +COPY . /backend/
плюс строка новая

2021-09-17 20:40 UTC, vrppaul commented on backend/generator/core/settings.py
> +ALLOWED_HOSTS = ['*']
а точно хотим все хосты позволять? или это лишь на пока? тогда надо ишью делать?

2021-09-17 20:40 UTC, vrppaul commented on backend/generator/core/settings.py
> +}
у тебя есть бд, но она работает независимо от конфигурации в докере. надо с помощью енва соединить или вообще ее не решать

2021-09-17 20:40 UTC, vrppaul commented on docker-compose.yml
> +  web:
не веб давай, а `backend`

2021-09-17 20:40 UTC, vrppaul commented on docker-compose.yml
> +      POSTGRES_HOST: db
это у тебя нигде не используется

2021-09-17 20:40 UTC, vrppaul commented on backend/Dockerfile
> +COPY . /backend/
у нас, кстати, в линкере ошибка, так как мы копируем все, а потом в докеркомпозе еще и вольюм создаем

2021-09-17 20:40 UTC, vrppaul commented on docker-compose.yml
> +    container_name: cv_generator_backend_web
зачем и веб и бэкенд?

2021-09-17 20:40 UTC, vrppaul commented on docker-compose.yml
> +      - ./backend/:/backend
вот тут интересный вопрос: мы и копируем все файлы бэкенда в докерфайле, а потом на них же создаем вольюм

2021-09-17 20:40 UTC, vrppaul commented on docker-compose.yml
> +    container_name: cv_generator_backend_db
у нас бд для всего проекта, так что тут backend можно убрать

2021-09-17 20:40 UTC, vrppaul commented on docker-compose.yml
> +      dockerfile: Dockerfile
я думаю, что этот файл можно сразу назвать `Dockerfile.dev`, так как он будет запускаться в докер композе, и не надо будет вводить название кастомного файла

2021-09-18 01:19 UTC, artemjasan commented on backend/Dockerfile
> +ENV POETRY_VERSION=1.1.8
Советуют сделать такую же как и на локале на компе, у нас там у всех 1.1.8 вопрос тогда может нам в поетри заложить версию? Сейчас у нас >= 1.0.0

2021-09-18 01:22 UTC, artemjasan commented on backend/Dockerfile
> +RUN pip install --no-cache-dir "poetry==$POETRY_VERSION"
У докера так себе поддержка написания мульти команд а писать через \ &&  мне кажется не так хорошо выглядит

2021-09-18 01:23 UTC, artemjasan commented on docker-compose.yml
> +    container_name: cv_generator_backend_web
Чтобы потом разделить фронт веб от Бека веба

2021-09-18 01:24 UTC, artemjasan commented on docker-compose.yml
> +    container_name: cv_generator_backend_db
Тут согласен, не подумал

2021-09-18 01:24 UTC, artemjasan commented on docker-compose.yml
> +      dockerfile: Dockerfile
Ок

2021-09-18 01:27 UTC, artemjasan commented on backend/Dockerfile
> +COPY poetry.lock pyproject.toml /backend/
Хорошо, я писал это явно чтобы было понятнее

2021-09-18 05:36 UTC, vrppaul commented on backend/Dockerfile
> +RUN pip install --no-cache-dir "poetry==$POETRY_VERSION"
Не получится просто установить поетри в той же строке и таким же способом как пипии сетаптулз? Я вижу, что там апгрейд, но если пакета нет, он вроде все равно устанавливает его

2021-09-18 05:37 UTC, vrppaul commented on docker-compose.yml
> +    container_name: cv_generator_backend_web
Я просто думаю, что слово веб можно убрать, у нас не настолько большой проект будет)

2021-09-18 08:05 UTC, artemjasan commented on backend/Dockerfile
> +RUN pip install --no-cache-dir "poetry==$POETRY_VERSION"
Попробую сегодня, если честно не видел. Напишу сюда результат

2021-09-18 08:06 UTC, artemjasan commented on docker-compose.yml
> +    container_name: cv_generator_backend_web
Понял) уберу

2021-09-18 10:46 UTC, artemjasan commented on backend/Dockerfile
> +ENV PIP_DISABLE_PIP_VERSION_CHECK=on
так как версия питона у нас очень свежая я бы тогда просто всегда делал апгрейд пипа) мне это кажется логичным

2021-09-19 09:56 UTC, artemjasan commented on docker-compose.yml
> +      - ./backend/:/backend
а разве это не правильно?

2021-09-19 10:03 UTC, artemjasan commented on docker-compose.yml
> +      POSTGRES_HOST: db
убираем)

2021-09-19 10:04 UTC, artemjasan commented on backend/Dockerfile
> +COPY . /backend/
а как правильно должно быть? я смотрю мануалы -везде примерно так делают

2021-09-19 10:05 UTC, artemjasan commented on backend/Dockerfile
> +ENV POETRY_VERSION=1.1.8
Я пробовал с той которая у меня стоит локально - но работает и без лока

2021-09-19 12:04 UTC, vrppaul commented on docker-compose.yml
> +      - ./backend/:/backend
Мы делаем одно и то же действие: копируем все файлы, а потом эти файлы заменяем маппингом вольюма

2021-09-19 12:06 UTC, vrppaul commented on backend/Dockerfile
> +COPY . /backend/
Ну подумай сам: мы копируем файлы, а потом просто на эту же директорию навешиваем мапппинг вольюма

2021-09-19 12:10 UTC, vrppaul commented on docker-compose.yml
> +      dockerfile: Dockerfile
Ну прод образ генерируется без композа, то есть существует возможность, что придется вручную писать docker build ... . Когда у тебя докерфайл с названием типа Dockerfile.prod, то тебе придется в эту команду ещё и добавлять название файла. Это лишнее телодвижение, потому мне кажется имеет смысл назвать Dockerfile только файл продукционного образа, чтобы не писать лишние параметры в команду. Так как ты всего один раз в докеркомпозе прописываешь название необходимого файла, то тебе неважно, какое он будет иметь название, поэтому такие файлы можно спокойно назвать Dockerfile.dev

2021-09-19 16:23 UTC, artemjasan commented on backend/Dockerfile
> +COPY . /backend/
Да, как раз вот сегодня смотрел мануалы. Я думаю нет смысла тогда в докерфале последнюю команду copy, раз в компоузе уже настраиваем маутинг

2021-09-19 16:25 UTC, artemjasan commented on docker-compose.yml
> +      dockerfile: Dockerfile
Понял

2021-09-19 17:53 UTC, vrppaul commented on backend/generator/core/settings.py
> +}
Вот это ещё исправить надо

2021-09-19 17:56 UTC, vrppaul requested changes
Ещё надо изменить веб на backend
Настройки бд остались независимыми от докера, нужно, чтобы они принимали из енва или дефолт

2021-09-20 10:58 UTC, vrppaul requested changes

2021-09-20 10:58 UTC, vrppaul commented on docker-compose.yml
> +    command: python /backend/generator/manage.py runserver 0.0.0.0:8000
Тут не достаточно будет оставить лишь `python generator/manage.py runserver`, так как эта команда передается в контейнер, а в нем мы уже в директории `backend`?

2021-09-20 10:58 UTC, vrppaul commented on backend/Dockerfile.dev
> +RUN pip install --no-cache-dir --upgrade pip setuptools && pip --no-cache-dir install poetry
Тут не получится `pip install --no-cache-dir --upgrade pip setuptools poetry`? Я это имел в виду в прошлом ревью. Если нет, то стоит оставить как две команды

2021-09-20 12:23 UTC, artemjasan commented on docker-compose.yml
> +    command: python /backend/generator/manage.py runserver 0.0.0.0:8000
Попробую вечером и напишу

2021-09-20 13:05 UTC, artemjasan commented on backend/Dockerfile.dev
> +RUN pip install --no-cache-dir --upgrade pip setuptools && pip --no-cache-dir install poetry
Как домой приду, ровноу попробую

2021-09-20 17:37 UTC, artemjasan commented on docker-compose.yml
> +    command: python /backend/generator/manage.py runserver 0.0.0.0:8000
да, все работает

2021-09-20 17:37 UTC, artemjasan commented on backend/Dockerfile.dev
> +RUN pip install --no-cache-dir --upgrade pip setuptools && pip --no-cache-dir install poetry
все хорошо

2021-09-20 17:41 UTC, vrppaul approved these changes

2021-09-20 17:47 UTC, merged