Init pytest [WIP]
LinkerApplication/cv-generator pull request #29
Opened 2021-09-24 14:50 UTC by artemjasan

Добавлена инициализация пайтеста в проект, созданы фактории.

Необходимо доделать:

- настроить правильную интерпретацию для поля experience (В модели у нас DateRangeField PostgreSQL). Нужен совет
нашел вот это https://factoryboy.readthedocs.io/en/stable/fuzzy.html#fuzzydate   - но я не уверен.

- есть вопросы по поводу связи юзера и профайл, сейчас я сделал как пост генерейнш, что мне кажется как раз наш случай. Но тоже необходим совет

Closes #15

2021-09-25 08:16 UTC, vrppaul requested changes
Очень много закоментированного кода, сразу делай рефактор всего этого

2021-09-25 08:16 UTC, vrppaul commented on backend/generator/profile/tests/factories.py
> +    number = factory.Sequence(lambda n: f'{n}_Number_profile')
У них там разве нет сразу поля с телефоном? Если и нет, то я бы как-то иначе генерировал телефон, нежели число и буквы, я таких телефонов не видел)

2021-09-25 08:16 UTC, vrppaul commented on backend/generator/profile/tests/factories.py
> +class UserFactory(factory.Factory):
Вот хороший пример из документации, как это можно сделать. Смотрел? https://factoryboy.readthedocs.io/en/stable/recipes.html#example-django-s-profile

2021-09-25 08:16 UTC, vrppaul commented on backend/generator/profile/tests/factories.py
> +    # experience  = factory.
Как я и писал, если это поле из себя представляет тупл, то просто генерируй тупл двух дат

2021-09-25 08:16 UTC, vrppaul commented on backend/generator/profile/tests/conftest.py
> +# TODO : Uncomment after integration custom user model
Очень много закоментированного кода. У нас сразу можно сделать три клиента: апи, нерегистрированный и регистрированный

2021-09-25 08:16 UTC, vrppaul commented on backend/generator/profile/tests/conftest.py
> +# def staff_api_client(create_user: UserMaker, api_client: APIClient) -> APIClient:
Это смело можно удалять

2021-09-25 08:16 UTC, vrppaul commented on backend/generator/profile/tests/conftest.py
> +# def try_all_authentications_with_codes(
Вот это сразу можно менять

2021-09-25 08:18 UTC, vrppaul requested changes

2021-09-25 08:18 UTC, vrppaul commented on backend/generator/profile/tests/factories.py
> +    user = factory.SubFactory(UserFactory)
Проверь ещё раз модель

2021-09-25 19:32 UTC, ssyucfa commented on backend/generator/profile/tests/factories.py
> +    # experience  = factory.
если мы будем генерить тупл двух дат, то первая может быть меньше второй, это нам не нужно, так как нужно будет делать доп проверки, не? мб лучше готовый вариант использовать?

2021-09-25 19:39 UTC, artemjasan commented on backend/generator/profile/tests/factories.py
> +    number = factory.Sequence(lambda n: f'{n}_Number_profile')
Да, тут я чёт затупил. Думаю что есть, а если нет то сделаю чисто с цифрами

2021-09-25 19:41 UTC, vrppaul commented on backend/generator/profile/tests/factories.py
> +    # experience  = factory.
Ну так и надо сделать так, чтобы второе было больше первого
То, что вы скидывали, - возвращает дату, которая находится в указанных границах

2021-09-25 19:42 UTC, artemjasan commented on backend/generator/profile/tests/factories.py
> +class UserFactory(factory.Factory):
Прикольно а я нашел статью и на станке что норм пост сейв работает в 3. Надо было идти сразу в оф документы

2021-09-25 19:44 UTC, artemjasan commented on backend/generator/profile/tests/factories.py
> +    # experience  = factory.
А я не понимаю что из себя представляет поле. Написано возвращает тип в подобии [ ). Я вот как раз смотрю что из себя представляет это поле и в каком формате оно сохраняет даты

2021-09-25 19:45 UTC, vrppaul commented on backend/generator/profile/tests/factories.py
> +class UserFactory(factory.Factory):
Да, он норм работает, но у него синтаксис без тайпинга замороченный + он чаще на фк или м2м используется

2021-09-25 19:45 UTC, artemjasan commented on backend/generator/profile/tests/conftest.py
> +# def staff_api_client(create_user: UserMaker, api_client: APIClient) -> APIClient:
Ок

2021-09-25 19:46 UTC, vrppaul commented on backend/generator/profile/tests/factories.py
> +    # experience  = factory.
Тут один вариант, который не самый лучший, наверное: тупо взять в шелле попробовать создать экземпляр модели и посмотреть, что возвращает

2021-09-25 19:46 UTC, artemjasan commented on backend/generator/profile/tests/factories.py
> +    user = factory.SubFactory(UserFactory)
Хорошо

2021-09-25 19:55 UTC, artemjasan commented on backend/generator/profile/tests/conftest.py
> +# TODO : Uncomment after integration custom user model
Под апи ты имеешь ввиду apiclient как в линкере?

2021-09-25 19:56 UTC, artemjasan commented on backend/generator/profile/tests/conftest.py
> +# TODO : Uncomment after integration custom user model
Тут фактически можно удалить везде стафф и админа, так как по проекту это не предусмотрено - у меня такой план был и соответственно остальное подкорректировать

2021-09-25 20:02 UTC, vrppaul commented on backend/generator/profile/tests/conftest.py
> +# TODO : Uncomment after integration custom user model
Да, именно его

2021-09-25 20:02 UTC, vrppaul commented on backend/generator/profile/tests/factories.py
> +    user = factory.SubFactory(UserFactory)
Бывает)

2021-09-26 19:01 UTC, ssyucfa commented on backend/generator/profile/tests/factories.py
> +    # experience  = factory.
короче, [ это значит что дата включена в промежуток, ) это что нет

2021-09-27 18:04 UTC, vrppaul requested changes
как мы обсудили, стоит оставить только настройки, фабрики и фикстуры пока можно убрать

2021-09-27 18:42 UTC, artemjasan commented on backend/generator/profile/tests/factories.py
> +    # experience  = factory.
Ну это в дБ, а в питоне это просто тапл с 2 значениями

2021-09-27 21:33 UTC, vrppaul approved these changes
ок, напиши в канале, что миграций больше нет и почему

2021-09-28 11:54 UTC, merged