created new baseuser
LinkerApplication/cv-generator pull request #30
Opened 2021-09-27 19:19 UTC by ssyucfa

Создал юзера с email, но без username

2021-09-27 19:48 UTC, vrppaul requested changes
ты тестировал?

2021-09-27 19:48 UTC, vrppaul commented on backend/generator/user/managers.py
> +    def _create_user(self, email, password, **extra_fields):
тут вроде без нижнего подчеркивания

2021-09-27 19:52 UTC, ssyucfa commented on backend/generator/user/managers.py
> +    def _create_user(self, email, password, **extra_fields):
я поставил, потому что в UserManager было так, да и нигде не будем использовать это кроме, самого класса

2021-09-27 19:54 UTC, vrppaul commented on backend/generator/user/managers.py
> +    def _create_user(self, email, password, **extra_fields):
в юзер менеджер было `create_user`, которое использует `_create_user`. пожалуйста, изучи получше класс

2021-09-27 19:55 UTC, ssyucfa commented on backend/generator/user/managers.py
> +    def _create_user(self, email, password, **extra_fields):
а, да)))

2021-10-03 19:29 UTC, vrppaul requested changes
небольшие изменения надо сделать

2021-10-03 19:29 UTC, vrppaul commented on backend/generator/user/admin.py
> +# Register your models here.
надо зарегистрировать новую модель, чтобы она в админке была

2021-10-03 19:29 UTC, vrppaul commented on backend/generator/user/managers.py
> +from django.conf import settings
вот это у тебя после пре-коммита изменится

2021-10-03 19:29 UTC, vrppaul commented on backend/pytest.ini
> +python_files = tests.py test_*.py *_tests.py
оставь пустую строку, она нужна

2021-10-03 19:29 UTC, vrppaul commented on backend/generator/user/tests/test_creating_users.py
> +    user = User.objects.create_user(email='normal@user.com', password='foo')
вот на это надо будет создать фабрику, но это можно сделать в самостоятельном ревью

2021-10-03 19:29 UTC, vrppaul commented on backend/generator/user/tests/test_creating_users.py
> +        pass
получится здесь сделать вот так?
```suggestion
   with pytest.raises(AttributeError):
        user.username
```

2021-10-03 19:29 UTC, vrppaul commented on backend/generator/user/tests/test_creating_users.py
> +        pass
попробуй здесь сделать также, как и выше я писал

2021-10-03 19:29 UTC, vrppaul commented on backend/generator/user/tests/test_creating_users.py
> +        User.objects.create_user(email='', password="foo")
я бы это выделил до самостоятельного теста, который бы тестировал именно неуспешность создания

2021-10-03 19:29 UTC, vrppaul commented on backend/generator/user/tests/test_creating_users.py
> +        pass
+ это можно выделить в самостоятельные тест, который будет тестировать именно отсутствие юзернейма

2021-10-03 19:29 UTC, vrppaul commented on backend/generator/user/tests/test_creating_users.py
> +        pass
плюс можно выделить в самостоятельный тест

2021-10-03 19:29 UTC, vrppaul commented on backend/generator/user/tests/test_creating_users.py
> +        )
это можно в самостоятельный тест

2021-10-03 19:29 UTC, vrppaul commented on backend/generator/user/tests/test_creating_users.py
> +        User.objects.create_user(email='', password="foo")
добавь еще проверки на `None` на всякий случай

2021-10-05 17:22 UTC, vrppaul reviewed
Хорошо. У меня чисто пара вопросов, после ответа на них дам аппрув

2021-10-05 17:22 UTC, vrppaul commented on backend/generator/user/admin.py
> +    def get_form(self, request, obj=None, **kwargs):
Нифига, сколько всего чисто для хэша. Что это делает и зачем?

2021-10-05 17:22 UTC, vrppaul commented on backend/generator/user/models.py
> +    REQUIRED_FIELDS: List[str] = []
У нас у нас не 9 питон случайно в пайпроджекте? Если 9, то можем уже ставить `list[str]` вроде

2021-10-05 17:22 UTC, vrppaul commented on backend/generator/user/tests/test_creating_users.py
> +        pass
Не получится сделать, как я предложил?

2021-10-05 17:24 UTC, ssyucfa commented on backend/generator/user/admin.py
> +    def get_form(self, request, obj=None, **kwargs):
эта хрень открывает add_form, если объект только создается, а если нет то обычную форму открывает

2021-10-05 17:24 UTC, ssyucfa commented on backend/generator/user/models.py
> +    REQUIRED_FIELDS: List[str] = []
да, точно, просто ни разу не использовал typing

2021-10-05 17:25 UTC, ssyucfa commented on backend/generator/user/models.py
> +    REQUIRED_FIELDS: List[str] = []
Не получится сделать, как я предложил?
а что ты именно предложил, а то я так и не понял, вроде же убрал все в другие тесты

2021-10-05 17:25 UTC, ssyucfa commented on backend/generator/user/models.py
> +    REQUIRED_FIELDS: List[str] = []
а понял

2021-10-05 17:29 UTC, ssyucfa commented on backend/generator/user/tests/test_creating_users.py
> +        pass
не, там ошибки

2021-10-05 17:31 UTC, ssyucfa commented on backend/pytest.ini
> +python_files = tests.py test_*.py *_tests.py
а зачем, кстати?

2021-10-05 17:39 UTC, vrppaul approved these changes

2021-10-05 17:39 UTC, vrppaul commented on backend/generator/user/admin.py
> +    def get_form(self, request, obj=None, **kwargs):
все, я сам все попробовал и теперь понимаю, о чем ты, хорошая работа

2021-10-05 17:40 UTC, merged