create endpoints and tests for them
LinkerApplication/cv-generator pull request #40
Opened 2021-10-26 10:12 UTC by ssyucfa

Сделал создание профиля, опыта 
Добавил разрешения для них
Создал фабрики для них
Сделал тесты
Добавил докстринги

2021-10-29 22:18 UTC, vrppaul requested changes

2021-10-29 22:18 UTC, vrppaul commented on backend/generator/profile/tests/test_profile_view_set.py
> +    profile.save()
мне кажется, что здесь будет проще принимать фикстуру незарегистрированного `api_clienta`, потом вручную делать `force_authenticate`, и потом уже создавать профиль, передавая ему нужного юзера. другой вариант сделать для этого отдельную фикстуру, чтобы не переписывать всюду код

2021-10-29 22:18 UTC, vrppaul commented on backend/generator/profile/tests/test_profile_view_set.py
> +                    ("since", str(experience.since)),
у нас они в виде datetime объекта хранятся?

2021-10-29 22:18 UTC, vrppaul commented on backend/generator/profile/tests/test_profile_view_set.py
> +    registered_api_client.handler._force_user.save()
это точно нужно? нам никогда не надо было так делать

2021-10-29 22:18 UTC, vrppaul commented on backend/generator/profile/tests/test_experience_view_set.py
> +    )
точно не получится просто с диктом сравнить?

2021-10-29 22:25 UTC, ssyucfa commented on backend/generator/profile/tests/test_experience_view_set.py
> +    )
да, там ошибка

2021-10-29 22:28 UTC, ssyucfa commented on backend/generator/profile/tests/test_profile_view_set.py
> +                    ("since", str(experience.since)),
да

2021-10-29 22:28 UTC, ssyucfa commented on backend/generator/profile/tests/test_profile_view_set.py
> +                    ("since", str(experience.since)),
просто date

2021-10-29 22:28 UTC, ssyucfa commented on backend/generator/profile/urls.py
> +router.register(r"experience", views.ExperienceViewSet, basename="experience")
ок

2021-10-29 22:29 UTC, ssyucfa commented on backend/generator/profile/tests/test_profile_view_set.py
> +    registered_api_client.handler._force_user.save()
да, ошибка

2021-10-29 22:31 UTC, ssyucfa commented on backend/generator/profile/tests/test_profile_view_set.py
> +    profile.save()
не не будет, нам все равно придется сохранять юзера, а так да, можно сделать фикстуру

2021-10-29 22:45 UTC, artemjasan commented on backend/generator/profile/tests/test_experience_view_set.py
> +    )
Странно, что ему там важно такое, наврятли порядок добавления?

2021-10-29 22:50 UTC, ssyucfa commented on backend/generator/profile/views.py
> +    permission_class_action_mapping = {"create": [CreateProfileOnlyOneTime]}
что именно не понял?

2021-10-29 22:50 UTC, ssyucfa commented on backend/generator/profile/views.py
> +    permission_class_action_mapping = {"create": [CreateExperiencePermission]}
что именно не понял?

2021-10-29 22:50 UTC, ssyucfa commented on backend/generator/profile/permissions.py
> +        return bool(request.user and request.user.is_authenticated and not has_profile)
в бизнес логику выведу, а где ее потом использовать?

2021-10-29 22:51 UTC, ssyucfa commented on backend/generator/profile/permissions.py
> +        return bool(request.user and request.user.is_authenticated and has_profile)
разве это тоже не пермишон, тип, ты можешь создавать опыт, пока у тебя нету профиля

2021-10-30 08:25 UTC, vrppaul commented on backend/generator/profile/permissions.py
> +        return bool(request.user and request.user.is_authenticated and has_profile)
Пермишн возвращает 403 и говорит, что человек не имеет разрешение. То есть, например, человек, который не создавал опыт, не имеет разрешение его исправлять. Здесь мы хотим посмотреть, имеет ли человек профиль, и если да, то он может создавать опыт. То есть здесь нам надо знать уже бизнес логику приложения, и раз так, то это должно быть в бизнес логике. Это не имеет связи с authorization процессом

2021-10-30 08:26 UTC, vrppaul commented on backend/generator/profile/permissions.py
> +        return bool(request.user and request.user.is_authenticated and not has_profile)
Во вьюхе или в других сервисах

2021-10-30 08:28 UTC, vrppaul commented on backend/generator/profile/views.py
> +    permission_class_action_mapping = {"create": [CreateProfileOnlyOneTime]}
Да я просто на всякий случай уточнил то, что писал выше насчёт разрешений

2021-10-30 10:31 UTC, vrppaul requested changes

2021-10-30 10:31 UTC, vrppaul commented on backend/generator/profile/tests/test_experience_view_set.py
> +    print(experience.since)
все принты надо убрать

2021-11-01 15:18 UTC, vrppaul commented on backend/generator/user/tests/factories.py
> +class UserFactory(factory.Factory):
я нашел причину ошибки. здесь должен быть тоже `factory.django.DjangoModelFactory`. у нас и в линкере такая ошибка. если здесь сделать джанго фактори, то можно не сохранять юзера в тестах

2021-11-01 15:21 UTC, ssyucfa commented on backend/generator/profile/tests/test_experience_view_set.py
> +    print(experience.since)
о, а то я его искал искал, так и не смог найти

2021-11-27 17:06 UTC, vrppaul requested changes
пока все, что нашел. я бы еще в чате разобрал, какие тесты кейсы уже готовы и какие стоило бы сделать

2021-11-27 17:06 UTC, vrppaul commented on backend/generator/profile/tests/test_experience_view_set.py
> +    assert user != registered_api_client.handler._force_user
это всегда будет True, тут нет смысла это проверять

2021-11-27 17:06 UTC, vrppaul commented on backend/generator/profile/tests/test_profile_view_set.py
> +    assert response.status_code == 403
я даже не знаю, стоит ли запрещать просматривать профили. в теории потом можно расширить функционал и сделать возможность шеринга профилей, чтобы можно было быстро скидывать, например, работодателям, чтобы они сами могли печатать резюме. что думаете?

2021-11-27 17:06 UTC, vrppaul commented on backend/generator/profile/tests/test_profile_view_set.py
> +    assert response.status_code == 400
тут все-таки должен быть 401, а не 400. потому что мы хотим показать, что надо зарегистрироваться, чтобы можно было создавать профиль

2021-11-27 17:06 UTC, vrppaul commented on backend/generator/profile/tests/test_profile_view_set.py
> +        client = api_client
опять же для анонимного должно быть 401

2021-11-27 17:06 UTC, vrppaul commented on backend/generator/profile/tests/test_profile_view_set.py
> +def test_user_has_profile_trying_to_one_more(
это не то же самое, что тут? test_user_has_profile_trying_to_create_second_profile

2021-11-27 19:55 UTC, ssyucfa commented on backend/generator/profile/permissions.py
> +class CanModifyProfileOrReadOnly(permissions.BasePermission):
в прошлый раз ты мне сказал так назвать)

2021-11-27 20:03 UTC, vrppaul commented on backend/generator/profile/permissions.py
> +class CanModifyProfileOrReadOnly(permissions.BasePermission):
да, мой косяк, согласен. в прошлый раз плохо вник в проблематику. теперь мне кажется, что лучше было бы, чтобы более общее название было после прочтения всего пр

2021-12-04 20:35 UTC, ssyucfa commented on backend/generator/profile/tests/test_profile_view_set.py
> +    assert response.status_code == 403
не, не, зачем, я не думаю, что все захотят, чтобы просматривали профиля, да и смысл, ну только, если работодателям скинуть

2021-12-04 20:40 UTC, ssyucfa commented on backend/generator/profile/tests/test_profile_view_set.py
> +    assert response.status_code == 400
а как сделать, тип во вью доп проверку сделать?

2021-12-04 20:42 UTC, vrppaul commented on backend/generator/profile/tests/test_profile_view_set.py
> +    assert response.status_code == 403
давай тогда пока оставим так. потом добавим фичу, что пользователь может сокрыть или открыть свой профиль

2021-12-04 20:42 UTC, vrppaul commented on backend/generator/profile/tests/test_profile_view_set.py
> +    assert response.status_code == 400
да, добавить пермишн во вьюху

2021-12-04 20:51 UTC, ssyucfa commented on backend/generator/profile/tests/test_experience_view_set.py
> +    profile.save()
как то сложно, не, только в этом пришлось сделать save

2021-12-04 20:53 UTC, ssyucfa commented on backend/generator/profile/views.py
> +    permission_classes = [ModifyExperienceOrReadOnlyPermission]
вроде не может создать, есть же проверка в тестах

2021-12-04 20:56 UTC, ssyucfa commented on backend/generator/profile/tests/test_experience_view_set.py
> +from typing import Type
окей

2021-12-04 20:57 UTC, ssyucfa commented on backend/generator/profile/views.py
> +        serializer.save(profile=self.request.user.profile)
чет не понял, если честно

2021-12-04 21:03 UTC, vrppaul commented on backend/generator/profile/tests/test_experience_view_set.py
> +    profile.save()
не сложно, все норм) посмотри в линкере в последнем пр, там подобное

2021-12-05 12:42 UTC, vrppaul commented on backend/generator/profile/views.py
> +    permission_classes = [ModifyExperienceOrReadOnlyPermission]
у тебя аноним может создать опыт, и даже в тестах это видно

2021-12-05 12:42 UTC, vrppaul commented on backend/generator/profile/views.py
> +        serializer.save(profile=self.request.user.profile)
я к тому, что в твоем варианте делается два запроса в бд: один при проверке, может ли пользователь создавать профиль и при получении профиля из реквеста
я предлагаю немного упростить обращения в бд тем способом, что ты просто получаешь профиль, и если его нет, то возвращает 400, если есть, то создаем опыт

2022-01-13 22:40 UTC, vrppaul requested changes
еще бы неплохо добавить тесты сервисов и уже будет готово

2022-01-13 22:40 UTC, vrppaul commented on backend/generator/profile/tests/test_experience_view_set.py
> +    assert response.status_code == status_code
я бы в эту функцию передавал только `experience_id`, а самим созданием его занимался снаружи, чтобы эта функция чисто проверяла ответы

2022-01-13 22:40 UTC, vrppaul commented on backend/generator/profile/tests/test_experience_view_set.py
> +    assert response.status_code == 403
а здесь не получится ту же самую функцию использовать?

2022-01-14 21:56 UTC, vrppaul approved these changes

2022-01-14 22:42 UTC, ssyucfa commented on backend/generator/profile/tests/test_experience_view_set.py
> +    assert response.status_code == status_code
а зачем? будет же избыточный код, 
`experience = experience_factory(profile=profile)`
одно и тоже два раза писать будем, а разницы нет

2022-01-15 14:26 UTC, vrppaul commented on backend/generator/profile/tests/test_experience_view_set.py
> +    assert response.status_code == status_code
код избыточный, но логика становится проще + полностью бы отвечала названию функции. а так просто много всего в функцию напихано

2022-01-15 19:16 UTC, merged